version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 5
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.31
    - 14.14.34
  - dependency-name: "@nestjs/core"
    versions:
    - 7.6.13
  - dependency-name: typescript
    versions:
    - 4.2.2
  - dependency-name: typeorm
    versions:
    - 0.2.30
  - dependency-name: "@nestjs/testing"
    versions:
    - 7.6.7
  - dependency-name: "@nestjs/common"
    versions:
    - 7.6.7
  - dependency-name: json-schema-to-typescript
    versions:
    - 10.1.3
